spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri:  https://github.com/iRahmanG/incident-management-config-repo.git
          username: iRahmanG
          password: ${GITHUB_TOKEN}
          default-label: main
          clone-on-start: true


server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka